version: '3'
services:
  worker-entityextract:
    depends_on:
        - rabbitmq
    image: worker-entityextract:1.0.0-SNAPSHOT
    env_file:
      - ./rabbitmq.env
    environment:
      CAF_WORKER_DATASTORE_PATH: /dataStore
      CAF_WORKER_INPUT_QUEUE: dataprocessing-fs-worker-entityextract-in
      CAF_WORKER_OUTPUT_QUEUE: document-input
    volumes:
      - worker-datastore:/dataStore
